apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}
  annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "CostCenter=LE"
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerSourceRanges: {{ .Values.service.sourceRanges }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
