---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-cockroachdb-certs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.cenm.storageClassShared }}
  resources:
    requests:
      storage: {{ .Values.certVolumeSize }}

