---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-cockroachdb-certs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.cenm.storageClassShared }}
  resources:
    requests:
      storage: {{ .Values.volumeSizeNotaryEtc }}


{{- if .Values.storage.persistentVolume.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
  - metadata:
      name: {{ .Values.prefix }}-cockroachdb-datadir
      labels:
        app.kubernetes.io/name: {{ template "cockroachdb.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
      {{- with .Values.storage.persistentVolume.labels }}
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.labels }}
        {{- toYaml . | nindent 10 }}
      {{- end }}
    {{- with .Values.storage.persistentVolume.annotations }}
      annotations: {{- toYaml . | nindent 10 }}
    {{- end }}
    spec:
      accessModes: ["ReadWriteOnce"]
    {{- if .Values.storage.persistentVolume.storageClass }}
    {{- if (eq "-" .Values.storage.persistentVolume.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: {{ .Values.storage.persistentVolume.storageClass | quote}}
    {{- end }}
    {{- end }}
      resources:
        requests:
          storage: {{ .Values.storage.persistentVolume.size | quote }}
{{- end }}
