---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-notary-service-conf
  labels:
    {{ include "notary-service.labels" . | nindent 4 }}
data:
  notary-service-initial-registration.sh: |+
    {{ tpl (.Files.Get "files/notary-service-initial-registration.sh") . | nindent 4 }}

  network-parameters-initial.conf: |+
    {{ tpl (.Files.Get "files/network-parameters-initial.conf") . | nindent 4 }}

  notary.conf: |+
    {{ tpl (.Files.Get "files/notary.conf") . | nindent 4 }}
