apiVersion: v1
kind: Service
metadata:
  name: {{ include "notary-service.fullname" . }}
  labels:
    {{- include "notary-service.labels" . | nindent 4 }}
spec:
# we need healthCheckNodePort set to get rid of logs pollution
{{- if (.Values.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.healthCheckNodePort }}
{{- end }}
  ports:
    - port: {{ .Values.p2pPort }}
      targetPort: {{ .Values.p2pPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.sshdPort }} 
      targetPort: {{ .Values.sshdPort }}
      protocol: TCP
      name: ssh
  selector:
    {{- include "notary-service.selectorLabels" . | nindent 4 }}
