---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "efs.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  file.system.id: {{ .Values.efs.id }}
  aws.region: {{ .Values.efs.region }}
  provisioner.name: aws.io/aws-efs
  dns.name: ""