---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-idman-etc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumeSizeIdmanEtc }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-idman-logs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumeSizeIdmanLogs }}
