# Default values for idman-ip.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

service:
  sourceRanges :
    - "10.1.0.0/16"
  type: LoadBalancer
  port: 10000

serviceRevocation:
  port: 5053

healthCheckNodePort: 0
